services:
  - type: web
    name: my-static-site
    env: static
    staticPublishPath: dist 
    headers:
      - for: "*.css"
        headers:
          - key: Content-Type
            value: text/css